API_URL = "http://api.openweathermap.org/data/2.5/weather"
API_KEY = ""
CITY = "Paris"
DB_NAME = "real_estate"
TABLE_NAME = "property_sales"
CSV_FILE_PATH = "/Users/macbookair/Documents/data_ing_project/pipeline_with_test_smock/data/input.csv"
